name: deploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/apiEcommerce:latest
      - name: Login to GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ secrets.GITHUB_USER }} --password-stdin
      - name: Build and push to GitHub Packages
        run: |
          docker build -t docker.pkg.github.com/${{ secrets.GITHUB_USER }}/apiEcommerce:latest .
          docker push docker.pkg.github.com/${{ secrets.GITHUB_USER }}/apiEcommerce:latest

